# Generated by Django 6.0.4 on 2026-05-31 20:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMachine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=255)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('fqdn', models.CharField(blank=True, max_length=512)),
                ('agent_token_hash', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_logged_user', models.CharField(blank=True, max_length=255)),
                ('os_name', models.CharField(blank=True, max_length=255)),
                ('os_version', models.CharField(blank=True, max_length=128)),
                ('windows_build', models.CharField(blank=True, max_length=128)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('serial_number', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['hostname', 'domain'],
                'indexes': [models.Index(fields=['hostname', 'domain'], name='agents_agen_hostnam_f8c43b_idx'), models.Index(fields=['last_seen_at'], name='agents_agen_last_se_05c7ed_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventorySnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('collected_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('hostname', models.CharField(max_length=255)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('logged_user', models.CharField(blank=True, max_length=255)),
                ('ips', models.JSONField(default=list)),
                ('os_name', models.CharField(blank=True, max_length=255)),
                ('os_version', models.CharField(blank=True, max_length=128)),
                ('windows_build', models.CharField(blank=True, max_length=128)),
                ('cpu', models.CharField(blank=True, max_length=255)),
                ('memory_total_bytes', models.BigIntegerField(blank=True, null=True)),
                ('disks', models.JSONField(default=list)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('serial_number', models.CharField(blank=True, max_length=255)),
                ('uptime_seconds', models.BigIntegerField(blank=True, null=True)),
                ('installed_software', models.JSONField(default=list)),
                ('defender_status', models.JSONField(default=dict)),
                ('raw_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_snapshots', to='agents.agentmachine')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['machine', '-received_at'], name='agents_inve_machine_21e76b_idx'), models.Index(fields=['hostname'], name='agents_inve_hostnam_699394_idx')],
            },
        ),
    ]
