# Generated by Django 6.0.5 on 2026-06-02 00:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agentmachine_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndpointAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(max_length=128)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical'), ('security', 'Security')], max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='open', max_length=16)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='agents.agentmachine')),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['endpoint', 'alert_type', 'status'], name='agents_endp_endpoin_f5510e_idx'), models.Index(fields=['severity', 'status'], name='agents_endp_severit_5626ef_idx'), models.Index(fields=['last_seen_at'], name='agents_endp_last_se_e66759_idx')],
            },
        ),
    ]
