# Generated by Django 6.0.5 on 2026-06-02 01:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_endpointalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointalert',
            name='muted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='endpointalert',
            name='muted_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='endpointalert',
            name='muted_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='endpointalert',
            name='resolution_type',
            field=models.CharField(blank=True, choices=[('automatic', 'Automatic'), ('manual', 'Manual')], max_length=16),
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('acknowledged', 'Acknowledged'), ('resolved_manual', 'Resolved manually'), ('resolved_automatic', 'Resolved automatically'), ('muted', 'Muted'), ('comment', 'Comment'), ('reopened', 'Reopened')], max_length=32)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('actor', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='agents.endpointalert')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['alert', '-created_at'], name='agents_aler_alert_i_f9dfe9_idx'), models.Index(fields=['event_type', '-created_at'], name='agents_aler_event_t_df004b_idx')],
            },
        ),
    ]
