# Generated by Django 6.0.5 on 2026-06-02 01:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_endpointalert_muted_at_endpointalert_muted_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=80)),
                ('severity', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('critical', 'Critical'), ('security', 'Security')], default='info', max_length=20)),
                ('actor_type', models.CharField(choices=[('system', 'System'), ('user', 'User'), ('agent', 'Agent'), ('scheduler', 'Scheduler')], default='system', max_length=30)),
                ('actor_name', models.CharField(blank=True, max_length=150)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='agents.endpointalert')),
                ('endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='agents.agentmachine')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='agents_audi_created_bfb2a7_idx'), models.Index(fields=['event_type'], name='agents_audi_event_t_b98bb2_idx'), models.Index(fields=['severity'], name='agents_audi_severit_8abba9_idx'), models.Index(fields=['actor_type'], name='agents_audi_actor_t_7c6389_idx'), models.Index(fields=['endpoint', '-created_at'], name='agents_audi_endpoin_f93288_idx'), models.Index(fields=['alert', '-created_at'], name='agents_audi_alert_i_4304d1_idx')],
            },
        ),
    ]
