# Generated by Django 6.0.5 on 2026-06-02 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_auditevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointalert',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='endpointalert',
            name='is_temporary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='endpointalert',
            name='source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddIndex(
            model_name='endpointalert',
            index=models.Index(fields=['is_temporary', 'expires_at'], name='agents_endp_is_temp_03a45c_idx'),
        ),
    ]
