# Generated by Django 6.0.5 on 2026-06-02 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_endpointalert_expires_at_endpointalert_is_temporary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmachine',
            name='agent_install_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='agentmachine',
            name='agent_mode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='agentmachine',
            name='agent_reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentmachine',
            name='agent_runtime',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='agentmachine',
            name='agent_runtime_version',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='agentmachine',
            name='agent_task_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='agentmachine',
            name='agent_version',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
