# Generated by Django 6.0.5 on 2026-06-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_agentmachine_agent_install_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmachine',
            name='agent_update_source',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
