# Generated by Django 6.0.5 on 2026-06-02 02:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_agentmachine_agent_update_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentEnrollmentToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('prefix', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('allowed_domain', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', 'expires_at'], name='agents_agen_is_acti_3fc362_idx'), models.Index(fields=['allowed_domain'], name='agents_agen_allowed_ac26be_idx'), models.Index(fields=['created_at'], name='agents_agen_created_e77a3e_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgentEnrollmentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=150)),
                ('domain', models.CharField(blank=True, max_length=150)),
                ('serial_number', models.CharField(blank=True, max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('denied', 'Denied'), ('expired', 'Expired'), ('inactive', 'Inactive'), ('usage_limit_reached', 'Usage limit reached'), ('invalid_token', 'Invalid token'), ('domain_denied', 'Domain denied'), ('error', 'Error')], max_length=30)),
                ('message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_logs', to='agents.agentmachine')),
                ('enrollment_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='agents.agentenrollmenttoken')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='agents_agen_status_75bb1d_idx'), models.Index(fields=['hostname'], name='agents_agen_hostnam_8f96b3_idx'), models.Index(fields=['domain'], name='agents_agen_domain_f52313_idx')],
            },
        ),
    ]
