# Generated by Django 6.0.5 on 2026-06-02 02:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_agentenrollmenttoken_agentenrollmentlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentenrollmentlog',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('denied', 'Denied'), ('expired', 'Expired'), ('inactive', 'Inactive'), ('usage_limit_reached', 'Usage limit reached'), ('invalid_token', 'Invalid token'), ('domain_denied', 'Domain denied'), ('manual_validation_required', 'Manual validation required'), ('invalid_manual_validation_token', 'Invalid manual validation token'), ('manual_validation_token_expired', 'Manual validation token expired'), ('manual_validation_token_used', 'Manual validation token used'), ('error', 'Error')], max_length=40),
        ),
        migrations.CreateModel(
            name='AgentManualValidationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('prefix', models.CharField(blank=True, max_length=30)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('used_by_hostname', models.CharField(blank=True, max_length=150)),
                ('used_by_domain', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_validation_tokens', to='agents.agentenrollmenttoken')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', 'expires_at'], name='agents_agen_is_acti_d7da81_idx'), models.Index(fields=['used_at'], name='agents_agen_used_at_c9ca0c_idx'), models.Index(fields=['created_at'], name='agents_agen_created_8986b7_idx')],
            },
        ),
    ]
