# Generated by Django 6.0.4 on 2026-06-08 14:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_alter_agentenrollmentlog_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwarePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('policy_type', models.CharField(choices=[('permitted', 'Permitido'), ('prohibited', 'Proibido'), ('required', 'Obrigatorio'), ('restricted', 'Restrito'), ('observed', 'Observado')], max_length=30)),
                ('software_name', models.CharField(max_length=180)),
                ('match_type', models.CharField(choices=[('contains', 'Contem'), ('equals', 'Igual'), ('starts_with', 'Comeca com')], default='contains', max_length=30)),
                ('publisher', models.CharField(blank=True, max_length=180)),
                ('version_rule', models.CharField(blank=True, max_length=180)),
                ('scope_type', models.CharField(choices=[('all', 'Todos os endpoints'), ('hostname_prefix', 'Hostname comeca com'), ('hostname_contains', 'Hostname contem'), ('domain', 'Dominio'), ('specific_endpoints', 'Endpoints especificos')], default='all', max_length=40)),
                ('scope_value', models.CharField(blank=True, max_length=255)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('security', 'Security'), ('warning', 'Warning'), ('info', 'Info')], default='info', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('monitor_only', models.BooleanField(default=False)),
                ('create_alert', models.BooleanField(default=True)),
                ('show_in_noc', models.BooleanField(default=True)),
                ('create_audit_event', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['policy_type', 'is_active'], name='agents_soft_policy__11e19d_idx'), models.Index(fields=['severity', 'is_active'], name='agents_soft_severit_140923_idx'), models.Index(fields=['scope_type'], name='agents_soft_scope_t_5a14eb_idx'), models.Index(fields=['software_name'], name='agents_soft_softwar_18de8e_idx')],
            },
        ),
        migrations.CreateModel(
            name='SoftwarePolicyException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True)),
                ('exception_type', models.CharField(choices=[('temporary', 'Temporaria'), ('permanent', 'Permanente')], default='temporary', max_length=30)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software_policy_exceptions', to='agents.agentmachine')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='agents.softwarepolicy')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['policy', 'is_active'], name='agents_soft_policy__7e3259_idx'), models.Index(fields=['endpoint', 'is_active'], name='agents_soft_endpoin_06e030_idx'), models.Index(fields=['exception_type', 'expires_at'], name='agents_soft_excepti_af87bf_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('policy', 'endpoint'), name='unique_active_software_policy_exception')],
            },
        ),
    ]
