# Generated by Django 6.0.4 on 2026-06-08 18:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0011_softwarepolicy_softwarepolicyexception'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwarePolicyViolation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('software_name', models.CharField(blank=True, max_length=180)),
                ('software_version', models.CharField(blank=True, max_length=120)),
                ('publisher', models.CharField(blank=True, max_length=180)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('ignored', 'Ignored'), ('exception_applied', 'Exception applied')], default='open', max_length=30)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('security', 'Security'), ('warning', 'Warning'), ('info', 'Info')], max_length=30)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_reason', models.CharField(blank=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software_policy_violations', to='agents.endpointalert')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software_policy_violations', to='agents.agentmachine')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='agents.softwarepolicy')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software_policy_violations', to='agents.inventorysnapshot')),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['policy', 'endpoint', 'status'], name='agents_soft_policy__1a5125_idx'), models.Index(fields=['endpoint', 'status', '-last_seen_at'], name='agents_soft_endpoin_0baa74_idx'), models.Index(fields=['severity', 'status'], name='agents_soft_severit_53cc4b_idx'), models.Index(fields=['software_name'], name='agents_soft_softwar_0a2111_idx')],
            },
        ),
    ]
