# Generated by Django 6.0.4 on 2026-06-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0012_softwarepolicyviolation'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='softwarepolicyviolation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('policy', 'endpoint', 'software_name'), name='unique_open_software_policy_violation'),
        ),
    ]
