# Generated by Django 6.0.4 on 2026-06-09 19:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0013_softwarepolicyviolation_unique_open_software_policy_violation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwarePolicyTargetEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targeted_software_policies', to='agents.agentmachine')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_endpoints', to='agents.softwarepolicy')),
            ],
            options={
                'ordering': ['endpoint__hostname'],
                'indexes': [models.Index(fields=['policy'], name='agents_soft_policy__dd14ec_idx'), models.Index(fields=['endpoint'], name='agents_soft_endpoin_e29a21_idx')],
                'constraints': [models.UniqueConstraint(fields=('policy', 'endpoint'), name='unique_software_policy_target_endpoint')],
            },
        ),
    ]
