# Generated by Django 6.0.4 on 2026-06-10 17:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0014_softwarepolicytargetendpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='running', max_length=20)),
                ('triggered_by', models.CharField(default='manual', max_length=80)),
                ('dry_run', models.BooleanField(default=False)),
                ('total_tasks', models.PositiveIntegerField(default=0)),
                ('successful_tasks', models.PositiveIntegerField(default=0)),
                ('failed_tasks', models.PositiveIntegerField(default=0)),
                ('skipped_tasks', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['status', '-started_at'], name='agents_main_status_fc2008_idx'), models.Index(fields=['-started_at'], name='agents_main_started_b8a206_idx'), models.Index(fields=['dry_run', '-started_at'], name='agents_main_dry_run_1c71d5_idx')],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceTaskResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=20)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('output', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_results', to='agents.maintenancerun')),
            ],
            options={
                'ordering': ['started_at'],
                'indexes': [models.Index(fields=['run', 'started_at'], name='agents_main_run_id_73b939_idx'), models.Index(fields=['task_name'], name='agents_main_task_na_c80bf0_idx'), models.Index(fields=['status'], name='agents_main_status_0ebf89_idx')],
            },
        ),
    ]
