# Generated by Django 6.0.5 on 2026-07-09 16:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0015_maintenancerun_maintenancetaskresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('force_inventory', 'Force inventory'), ('collect_disks', 'Collect disks'), ('collect_security', 'Collect security'), ('collect_software', 'Collect software'), ('ping', 'Ping'), ('collect_logs', 'Collect logs'), ('windows_update_scan', 'Windows Update scan')], max_length=80)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('stdout', models.TextField(blank=True)),
                ('stderr', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('queued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='agents.agentmachine')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['endpoint', 'status', '-created_at'], name='agents_agen_endpoin_f78812_idx'), models.Index(fields=['status', '-created_at'], name='agents_agen_status_6512e2_idx'), models.Index(fields=['job_type', '-created_at'], name='agents_agen_job_typ_3c4c26_idx')],
            },
        ),
    ]
