# Generated by Django 6.0.5 on 2026-07-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0016_agentjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmachine',
            name='machine_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
