# Generated by Django 6.0.5 on 2026-07-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0018_agentjob_update_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentjob',
            name='job_type',
            field=models.CharField(choices=[('force_inventory', 'Force inventory'), ('collect_disks', 'Collect disks'), ('collect_security', 'Collect security'), ('collect_software', 'Collect software'), ('ping', 'Ping'), ('collect_logs', 'Collect logs'), ('windows_update_scan', 'Windows Update scan'), ('update_agent', 'Update agent'), ('restart_agent', 'Restart agent')], max_length=80),
        ),
    ]
