# Generated by Django 6.0.5 on 2026-07-20 13:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0019_alter_agentjob_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentjob',
            name='attempt',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='agentjob',
            name='correlation_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='agentjob',
            name='error_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='agentjob',
            name='output_truncated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agentjob',
            name='result_id',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='agentjob',
            name='result_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentjob',
            name='timeout_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agentjob',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('timed_out', 'Timed out'), ('duplicate', 'Duplicate'), ('unsupported', 'Unsupported'), ('invalid_parameters', 'Invalid parameters'), ('interrupted', 'Interrupted'), ('rolled_back', 'Rolled back'), ('rollback_failed', 'Rollback failed')], default='queued', max_length=20),
        ),
        migrations.CreateModel(
            name='AgentJobResultReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result_id', models.CharField(max_length=80, unique=True)),
                ('payload_sha256', models.CharField(max_length=64)),
                ('first_payload', models.JSONField(blank=True, default=dict)),
                ('conflict_count', models.PositiveIntegerField(default=0)),
                ('last_conflict_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_result_receipts', to='agents.agentmachine')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_receipts', to='agents.agentjob')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['endpoint', '-received_at'], name='agents_agen_endpoin_d40973_idx'), models.Index(fields=['job', '-received_at'], name='agents_agen_job_id_e8a69e_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgentOperationalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installed_version', models.CharField(blank=True, max_length=50)),
                ('available_version', models.CharField(blank=True, max_length=50)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('last_inventory_at', models.DateTimeField(blank=True, null=True)),
                ('last_agent_start_at', models.DateTimeField(blank=True, null=True)),
                ('agent_uptime_seconds', models.BigIntegerField(blank=True, null=True)),
                ('service_status', models.CharField(blank=True, max_length=80)),
                ('current_user', models.CharField(blank=True, max_length=255)),
                ('current_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('pending_result_count', models.PositiveIntegerField(default=0)),
                ('running_job_count', models.PositiveIntegerField(default=0)),
                ('last_error_code', models.CharField(blank=True, max_length=80)),
                ('last_error_message', models.TextField(blank=True)),
                ('last_error_component', models.CharField(blank=True, max_length=80)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('update_id', models.CharField(blank=True, max_length=80)),
                ('update_job_id', models.CharField(blank=True, max_length=80)),
                ('from_version', models.CharField(blank=True, max_length=50)),
                ('target_version', models.CharField(blank=True, max_length=50)),
                ('update_current_stage', models.CharField(blank=True, max_length=80)),
                ('update_status', models.CharField(blank=True, max_length=40)),
                ('update_started_at', models.DateTimeField(blank=True, null=True)),
                ('update_completed_at', models.DateTimeField(blank=True, null=True)),
                ('rollback_status', models.CharField(blank=True, max_length=40)),
                ('rollback_attempt', models.PositiveIntegerField(default=0)),
                ('health_check_confirmed', models.BooleanField(default=False)),
                ('update_error_code', models.CharField(blank=True, max_length=80)),
                ('update_error_message', models.TextField(blank=True)),
                ('rollback_error_code', models.CharField(blank=True, max_length=80)),
                ('rollback_error_message', models.TextField(blank=True)),
                ('package_url_sanitized', models.CharField(blank=True, max_length=500)),
                ('result_pending_count', models.PositiveIntegerField(default=0)),
                ('result_oldest_pending_at', models.DateTimeField(blank=True, null=True)),
                ('result_retrying_count', models.PositiveIntegerField(default=0)),
                ('result_quarantined_count', models.PositiveIntegerField(default=0)),
                ('result_queue_full', models.BooleanField(default=False)),
                ('result_last_send_error', models.TextField(blank=True)),
                ('health_indicator', models.CharField(choices=[('healthy', 'Healthy'), ('attention', 'Attention'), ('critical', 'Critical'), ('offline', 'Offline')], default='healthy', max_length=20)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operational_status', to='agents.agentmachine')),
            ],
            options={
                'ordering': ['endpoint__hostname'],
                'indexes': [models.Index(fields=['health_indicator'], name='agents_agen_health__892435_idx'), models.Index(fields=['service_status'], name='agents_agen_service_25e92f_idx'), models.Index(fields=['update_status'], name='agents_agen_update__27a019_idx'), models.Index(fields=['result_queue_full'], name='agents_agen_result__99bb98_idx'), models.Index(fields=['last_error_code'], name='agents_agen_last_er_449106_idx')],
            },
        ),
    ]
