# Generated by Django 6.0.5 on 2026-07-23 14:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def create_default_release_groups(apps, schema_editor):
    group_model = apps.get_model('agents', 'AgentReleaseGroup')
    defaults = [
        ('Internal IT', 'internal-it', 'Equipe interna de TI'),
        ('Pilot', 'pilot', 'Endpoints do piloto controlado'),
        ('Workstations', 'workstations', 'Estacoes de trabalho'),
        ('Remote', 'remote', 'Endpoints remotos ou fora do dominio'),
        ('Servers', 'servers', 'Servidores'),
        ('Critical', 'critical', 'Endpoints criticos'),
        ('Manual', 'manual', 'Distribuicao manual'),
    ]
    for name, slug, description in defaults:
        group_model.objects.get_or_create(slug=slug, defaults={'name': name, 'description': description})


def remove_default_release_groups(apps, schema_editor):
    group_model = apps.get_model('agents', 'AgentReleaseGroup')
    group_model.objects.filter(slug__in=['internal-it', 'pilot', 'workstations', 'remote', 'servers', 'critical', 'manual']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0020_agentjob_attempt_agentjob_correlation_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentReleaseGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(create_default_release_groups, remove_default_release_groups),
        migrations.AddField(
            model_name='agentmachine',
            name='auto_update_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agentmachine',
            name='last_update_policy_evaluation_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentmachine',
            name='maintenance_window_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentmachine',
            name='maintenance_window_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentmachine',
            name='pinned_agent_version',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='agentmachine',
            name='update_channel',
            field=models.CharField(choices=[('development', 'Development'), ('pilot', 'Pilot'), ('stable', 'Stable')], db_index=True, default='stable', max_length=20),
        ),
        migrations.AddField(
            model_name='agentmachine',
            name='update_paused',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='agentmachine',
            name='update_policy',
            field=models.CharField(choices=[('manual', 'Manual'), ('notify_only', 'Notify only'), ('automatic', 'Automatic'), ('maintenance_window', 'Maintenance window')], db_index=True, default='manual', max_length=30),
        ),
        migrations.CreateModel(
            name='AgentRelease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=50, unique=True)),
                ('channel', models.CharField(choices=[('development', 'Development'), ('pilot', 'Pilot'), ('stable', 'Stable')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('validating', 'Validating'), ('available', 'Available'), ('paused', 'Paused'), ('revoked', 'Revoked'), ('superseded', 'Superseded')], db_index=True, default='draft', max_length=20)),
                ('package_url', models.URLField(max_length=1000)),
                ('checksum_url', models.URLField(blank=True, max_length=1000)),
                ('sha256', models.CharField(max_length=64)),
                ('size', models.BigIntegerField(default=0)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('minimum_updater_version', models.CharField(blank=True, max_length=50)),
                ('release_notes', models.TextField(blank=True)),
                ('rollout_percentage', models.PositiveSmallIntegerField(default=0)),
                ('rollout_paused', models.BooleanField(db_index=True, default=False)),
                ('mandatory', models.BooleanField(default=False)),
                ('revoked', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_releases', to=settings.AUTH_USER_MODEL)),
                ('replacement_release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_releases', to='agents.agentrelease')),
                ('allowed_groups', models.ManyToManyField(blank=True, related_name='releases', to='agents.agentreleasegroup')),
            ],
            options={
                'ordering': ['-released_at', '-created_at'],
                'permissions': [('view_agent_release_rollout', 'Can view agent release rollout'), ('create_agent_release_draft', 'Can create agent release draft'), ('publish_agent_release_development', 'Can publish development agent release'), ('promote_agent_release_pilot', 'Can promote agent release to pilot'), ('promote_agent_release_stable', 'Can promote agent release to stable'), ('pause_agent_release_rollout', 'Can pause agent release rollout'), ('revoke_agent_release', 'Can revoke agent release'), ('force_agent_update', 'Can force agent update')],
            },
        ),
        migrations.AddField(
            model_name='agentjob',
            name='agent_release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='agents.agentrelease'),
        ),
        migrations.AddField(
            model_name='agentmachine',
            name='rollout_groups',
            field=models.ManyToManyField(blank=True, related_name='endpoints', to='agents.agentreleasegroup'),
        ),
        migrations.CreateModel(
            name='AgentReleaseAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('paused', 'Paused'), ('resumed', 'Resumed'), ('promoted', 'Promoted'), ('revoked', 'Revoked'), ('endpoint_policy_changed', 'Endpoint policy changed')], max_length=60)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('channel_before', models.CharField(blank=True, max_length=20)),
                ('channel_after', models.CharField(blank=True, max_length=20)),
                ('rollout_before', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rollout_after', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='release_audits', to='agents.agentmachine')),
                ('release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to='agents.agentrelease')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_release_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', '-created_at'], name='agents_agen_action_02b1b9_idx'), models.Index(fields=['release', '-created_at'], name='agents_agen_release_859195_idx'), models.Index(fields=['endpoint', '-created_at'], name='agents_agen_endpoin_3d7933_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='agentrelease',
            index=models.Index(fields=['channel', 'status', '-released_at'], name='agents_agen_channel_d9bdca_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrelease',
            index=models.Index(fields=['revoked', 'rollout_paused'], name='agents_agen_revoked_dcaddf_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrelease',
            index=models.Index(fields=['version'], name='agents_agen_version_637a63_idx'),
        ),
    ]
