# Generated by Django 6.0.5 on 2026-08-04 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def normalize_existing_releases(apps, schema_editor):
    AgentRelease = apps.get_model('agents', 'AgentRelease')
    for release in AgentRelease.objects.all():
        if not release.source_channel:
            release.source_channel = release.channel or 'stable'
        if release.revoked or release.status == 'revoked':
            release.status = 'revoked'
            release.revoked = True
            if release.revoked_at is None:
                release.revoked_at = release.updated_at or release.created_at
        elif release.status in {'available', 'active'}:
            release.status = 'published'
        elif release.status == 'validating':
            release.status = 'draft'
        if release.status == 'paused':
            release.rollout_paused = True
        release.legacy_unsigned = True
        release.signature_valid = False
        release.save(update_fields=[
            'source_channel',
            'status',
            'revoked',
            'revoked_at',
            'rollout_paused',
            'legacy_unsigned',
            'signature_valid',
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0021_agentreleasegroup_agentmachine_auto_update_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentrelease',
            options={'ordering': ['-released_at', '-created_at'], 'permissions': [('view_agent_release_rollout', 'Can view agent release rollout'), ('create_agent_release_draft', 'Can create agent release draft'), ('publish_agentrelease', 'Can publish agent releases'), ('promote_agentrelease', 'Can promote agent releases'), ('promote_agentrelease_stable', 'Can promote agent releases to stable'), ('pause_agentrelease', 'Can pause agent releases'), ('revoke_agentrelease', 'Can revoke agent releases'), ('publish_agent_release_development', 'Can publish development agent release'), ('promote_agent_release_pilot', 'Can promote agent release to pilot'), ('promote_agent_release_stable', 'Can promote agent release to stable'), ('pause_agent_release_rollout', 'Can pause agent release rollout'), ('revoke_agent_release', 'Can revoke agent release'), ('force_agent_update', 'Can force agent update')]},
        ),
        migrations.AddField(
            model_name='agentmachine',
            name='is_pilot_endpoint',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='agentrelease',
            name='legacy_unsigned',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='agentrelease',
            name='manifest_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='agentrelease',
            name='manifest_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='agentrelease',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_agent_releases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentrelease',
            name='revocation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agentrelease',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentrelease',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_agent_releases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentrelease',
            name='signature_key_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='agentrelease',
            name='signature_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='agentrelease',
            name='signature_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='agentrelease',
            name='signature_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agentrelease',
            name='source_channel',
            field=models.CharField(blank=True, choices=[('development', 'Development'), ('pilot', 'Pilot'), ('stable', 'Stable')], db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='agentrelease',
            name='stable_approval_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agentrelease',
            name='superseded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentrelease',
            name='superseded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_agent_releases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentrelease',
            name='superseded_reason',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(normalize_existing_releases, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='agentrelease',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('paused', 'Paused'), ('revoked', 'Revoked'), ('superseded', 'Superseded')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='agentreleaseaudit',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('paused', 'Paused'), ('resumed', 'Resumed'), ('promoted', 'Promoted'), ('revoked', 'Revoked'), ('published', 'Published'), ('rollout_changed', 'Rollout changed'), ('superseded', 'Superseded'), ('immutability_blocked', 'Immutability blocked'), ('signature_failed', 'Signature failed'), ('endpoint_policy_changed', 'Endpoint policy changed')], max_length=60),
        ),
        migrations.AddIndex(
            model_name='agentrelease',
            index=models.Index(fields=['legacy_unsigned', 'signature_valid'], name='agents_agen_legacy__7072e5_idx'),
        ),
    ]
