# Generated by Django 6.0.5 on 2026-08-05 14:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0022_alter_agentrelease_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentReleaseSigningKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_id', models.CharField(max_length=120, unique=True)),
                ('algorithm', models.CharField(default='RSA-PSS-SHA256', max_length=40)),
                ('public_key_xml', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], db_index=True, default='active', max_length=20)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_agent_release_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['key_id'],
                'indexes': [models.Index(fields=['key_id', 'status'], name='agents_agen_key_id_9a6808_idx'), models.Index(fields=['status', 'valid_from', 'valid_until'], name='agents_agen_status_3db4bb_idx')],
            },
        ),
    ]
