# Generated by Django 6.0.5 on 2026-08-24 19:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0025_agentjob_uninstall_agent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentDeploymentToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('windows', 'Windows')], default='windows', max_length=20)),
                ('channel', models.CharField(choices=[('development', 'Development'), ('pilot', 'Pilot'), ('stable', 'Stable')], max_length=20)),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('prefix', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('installing', 'Installing'), ('completed', 'Completed'), ('expired', 'Expired'), ('failed', 'Failed')], db_index=True, default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('installing_at', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, max_length=80)),
                ('failure_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_deployment_tokens', to=settings.AUTH_USER_MODEL)),
                ('endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployment_tokens', to='agents.agentmachine')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deployment_tokens', to='agents.agentrelease')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['platform', 'status', '-created_at'], name='agents_agen_platfor_22372c_idx'), models.Index(fields=['release', '-created_at'], name='agents_agen_release_d11a8d_idx'), models.Index(fields=['expires_at', 'status'], name='agents_agen_expires_611700_idx')],
            },
        ),
    ]
