# Generated by Django 6.0.5 on 2026-08-27 14:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0027_agentjob_repair_agent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentmachine',
            options={'ordering': ['hostname', 'domain'], 'permissions': [('uninstall_agent', 'Can authorize NightOwl Agent uninstall')]},
        ),
        migrations.AddField(
            model_name='agentmachine',
            name='agent_lifecycle_status',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AddField(
            model_name='agentmachine',
            name='agent_uninstall_source',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='agentmachine',
            name='agent_uninstalled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentmachine',
            name='agent_uninstalled_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='agentmachine',
            name='last_installed_agent_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='agentmachine',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('unknown', 'Unknown'), ('uninstalled', 'Uninstalled')], default='unknown', max_length=16),
        ),
        migrations.CreateModel(
            name='AgentUninstallRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('uninstall', 'Uninstall'), ('purge', 'Purge')], default='uninstall', max_length=20)),
                ('source', models.CharField(choices=[('panel', 'Panel'), ('tray', 'Tray')], max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('waiting_for_agent', 'Waiting for agent'), ('dispatched', 'Dispatched'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('outcome_unknown', 'Outcome unknown')], db_index=True, default='requested', max_length=30)),
                ('requested_by', models.CharField(blank=True, max_length=150)),
                ('authorized_by', models.CharField(blank=True, max_length=150)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uninstall_request', to='agents.agentjob')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uninstall_requests', to='agents.agentmachine')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentLocalUninstallAuthorization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('authorized_by', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('active', 'Active'), ('consumed', 'Consumed'), ('expired', 'Expired'), ('revoked', 'Revoked')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_uninstall_authorizations', to='agents.agentmachine')),
                ('uninstall_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_authorizations', to='agents.agentuninstallrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='agentuninstallrequest',
            index=models.Index(fields=['endpoint', 'status', '-created_at'], name='agents_agen_endpoin_fb3290_idx'),
        ),
        migrations.AddIndex(
            model_name='agentuninstallrequest',
            index=models.Index(fields=['source', 'status'], name='agents_agen_source_6c7e92_idx'),
        ),
        migrations.AddIndex(
            model_name='agentuninstallrequest',
            index=models.Index(fields=['expires_at'], name='agents_agen_expires_651141_idx'),
        ),
        migrations.AddIndex(
            model_name='agentlocaluninstallauthorization',
            index=models.Index(fields=['endpoint', 'status', '-created_at'], name='agents_agen_endpoin_0edff7_idx'),
        ),
        migrations.AddIndex(
            model_name='agentlocaluninstallauthorization',
            index=models.Index(fields=['expires_at'], name='agents_agen_expires_8c4516_idx'),
        ),
    ]
