# Generated by Django 6.0.5 on 2026-09-02 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0028_alter_agentmachine_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentmachine',
            options={'ordering': ['hostname', 'domain'], 'permissions': [('uninstall_agent', 'Can authorize NightOwl Agent uninstall'), ('purge_agent', 'Can authorize NightOwl Agent purge')]},
        ),
    ]
