# Generated by Django 6.0.5 on 2026-09-17 14:52

from django.db import migrations, models
import re


def backfill_reported_versions_and_pilot(apps, schema_editor):
    machine_model = apps.get_model('agents', 'AgentMachine')
    group_model = apps.get_model('agents', 'AgentReleaseGroup')
    snapshots = apps.get_model('agents', 'InventorySnapshot')
    alias = schema_editor.connection.alias
    pilot, _ = group_model.objects.using(alias).get_or_create(slug='pilot', defaults={'name': 'Pilot'})
    for machine in machine_model.objects.using(alias).iterator():
        if machine.is_pilot_endpoint:
            machine.rollout_groups.add(pilot)
        fields = {}
        for snapshot in snapshots.objects.using(alias).filter(machine_id=machine.pk).order_by('-received_at', '-pk').iterator():
            payload = snapshot.raw_payload if isinstance(snapshot.raw_payload, dict) else {}
            agent = payload.get('agent') if isinstance(payload.get('agent'), dict) else {}
            collections = payload.get('collections') if isinstance(payload.get('collections'), dict) else {}
            inventory = collections.get('full_inventory') if isinstance(collections.get('full_inventory'), dict) else {}
            inventory_agent = inventory.get('agent') if isinstance(inventory.get('agent'), dict) else {}
            for field in ('updater_version', 'tray_version'):
                value = payload.get(field) or agent.get(field) or inventory.get(field) or inventory_agent.get(field)
                match = re.fullmatch(r'(\d+(?:\.\d+){1,3}(?:-[0-9A-Za-z][0-9A-Za-z.-]*)?)(?:\+[0-9A-Za-z.-]+)?', str(value or ''))
                if field not in fields and match:
                    fields[field] = match.group(1)[:50]
            if len(fields) == 2:
                break
        if fields:
            machine_model.objects.using(alias).filter(pk=machine.pk).update(**fields)


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0029_agentmachine_purge_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmachine',
            name='maintenance_window_timezone',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='agentmachine',
            name='tray_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='agentmachine',
            name='updater_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.RunPython(backfill_reported_versions_and_pilot, migrations.RunPython.noop),
    ]
