# Generated by Django 6.0.5 on 2026-09-17 18:12

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


def guard_rules(apps):
    campaign = apps.get_model('agents', 'AgentRolloutCampaign')
    wave = apps.get_model('agents', 'AgentRolloutWave')
    target = apps.get_model('agents', 'AgentRolloutTarget')
    mutable = {'state', 'current_wave', 'updated_at', 'started_at', 'paused_at', 'completed_at', 'aborted_at'}
    campaign_columns = [f.column for f in campaign._meta.fields if f.name not in mutable]
    wave_columns = [f.column for f in wave._meta.fields if f.name not in {'state', 'resume_state', 'updated_at', 'started_at', 'observation_started_at', 'completed_at'}]
    target_columns = [f.column for f in target._meta.fields]
    tables = [campaign._meta.db_table, wave._meta.db_table, target._meta.db_table]
    return tables, campaign_columns, wave_columns, target_columns


def install_guards(apps, schema_editor):
    tables, campaign_columns, wave_columns, target_columns = guard_rules(apps)
    c, w, t = tables
    vendor = schema_editor.connection.vendor
    if vendor not in {'sqlite', 'postgresql'}:
        raise RuntimeError('Rollout guards require SQLite or PostgreSQL')
    distinct = lambda cols: ' OR '.join(f'OLD."{col}" IS DISTINCT FROM NEW."{col}"' if vendor == 'postgresql' else f'OLD."{col}" IS NOT NEW."{col}"' for col in cols)
    frozen = lambda alias: f"EXISTS (SELECT 1 FROM {c} WHERE id={alias}.campaign_id AND state <> 'draft')"
    rules = [
        ('campaign_freeze', c, 'UPDATE', f"OLD.state <> 'draft' AND ({distinct(campaign_columns)})"),
        ('campaign_terminal', c, 'UPDATE', "OLD.state <> NEW.state AND NOT ((OLD.state='draft' AND NEW.state IN ('ready','aborted')) OR (OLD.state='ready' AND NEW.state IN ('running','aborted')) OR (OLD.state='running' AND NEW.state IN ('paused','completed','aborted')) OR (OLD.state='paused' AND NEW.state IN ('running','aborted')))"),
        ('campaign_wave', c, 'UPDATE', f'NEW.current_wave_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM {w} WHERE id=NEW.current_wave_id AND campaign_id=NEW.id)'),
        ('campaign_wave_insert', c, 'INSERT', f'NEW.current_wave_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM {w} WHERE id=NEW.current_wave_id AND campaign_id=NEW.id)'),
        ('wave_freeze', w, 'UPDATE', f"({frozen('OLD')} OR {frozen('NEW')}) AND ({distinct(wave_columns)})"),
        ('wave_insert', w, 'INSERT', frozen('NEW')),
        ('wave_delete', w, 'DELETE', frozen('OLD')),
        ('wave_transition', w, 'UPDATE', "OLD.state <> NEW.state AND NOT ((OLD.state='pending' AND NEW.state IN ('ready','cancelled')) OR (OLD.state='ready' AND NEW.state IN ('running','cancelled')) OR (OLD.state='running' AND NEW.state IN ('observing','paused','cancelled')) OR (OLD.state='observing' AND NEW.state IN ('completed','paused','cancelled')) OR (OLD.state='paused' AND (NEW.state='cancelled' OR NEW.state=OLD.resume_state)))"),
        ('target_freeze', t, 'UPDATE', f"({frozen('OLD')} OR {frozen('NEW')}) AND ({distinct(target_columns)})"),
        ('target_insert', t, 'INSERT', frozen('NEW')),
        ('target_delete', t, 'DELETE', frozen('OLD')),
        ('target_wave', t, 'INSERT', f'NEW.wave_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM {w} WHERE id=NEW.wave_id AND campaign_id=NEW.campaign_id)'),
        ('target_wave_update', t, 'UPDATE', f'NEW.wave_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM {w} WHERE id=NEW.wave_id AND campaign_id=NEW.campaign_id)'),
        ('wave_campaign', w, 'UPDATE', f'OLD.campaign_id <> NEW.campaign_id AND (EXISTS (SELECT 1 FROM {t} WHERE wave_id=OLD.id) OR EXISTS (SELECT 1 FROM {c} WHERE current_wave_id=OLD.id))'),
    ]
    for name, table, event, condition in rules:
        name = 'rollout_guard_' + name
        if vendor == 'sqlite':
            schema_editor.execute(f"CREATE TRIGGER {name} BEFORE {event} ON {table} WHEN {condition} BEGIN SELECT RAISE(ABORT, '{name}'); END")
        else:
            result = 'OLD' if event == 'DELETE' else 'NEW'
            # Serialize child changes with READY: a plain MVCC read can see draft
            # while approval holds the parent lock in another transaction.
            lock = ''
            if table in {w, t}:
                aliases = ['OLD'] if event == 'DELETE' else ['NEW'] if event == 'INSERT' else ['OLD', 'NEW']
                ids = ','.join(f'{alias}.campaign_id' for alias in aliases)
                lock = f'PERFORM 1 FROM {c} WHERE id IN ({ids}) ORDER BY id FOR UPDATE;'
            schema_editor.execute(f"CREATE FUNCTION {name}() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN {lock} IF {condition} THEN RAISE EXCEPTION '{name}' USING ERRCODE='23514'; END IF; RETURN {result}; END $$")
            schema_editor.execute(f'CREATE TRIGGER {name} BEFORE {event} ON {table} FOR EACH ROW EXECUTE FUNCTION {name}()')


def remove_guards(apps, schema_editor):
    c, w, t = guard_rules(apps)[0]
    names = {'campaign_freeze': c, 'campaign_terminal': c, 'campaign_wave': c, 'campaign_wave_insert': c,
             'wave_freeze': w, 'wave_insert': w, 'wave_delete': w, 'wave_transition': w, 'target_freeze': t,
             'target_insert': t, 'target_delete': t, 'target_wave': t, 'target_wave_update': t, 'wave_campaign': w}
    for name, table in names.items():
        name = 'rollout_guard_' + name
        if schema_editor.connection.vendor == 'sqlite':
            schema_editor.execute(f'DROP TRIGGER IF EXISTS {name}')
        else:
            schema_editor.execute(f'DROP TRIGGER IF EXISTS {name} ON {table}')
            schema_editor.execute(f'DROP FUNCTION IF EXISTS {name}()')


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0030_rollout_eligibility_contract'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRolloutCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('release_snapshot', models.JSONField(default=dict)),
                ('channel_snapshot', models.CharField(max_length=20)),
                ('state', models.CharField(choices=[('draft', 'draft'), ('ready', 'ready'), ('running', 'running'), ('paused', 'paused'), ('completed', 'completed'), ('aborted', 'aborted')], default='draft', max_length=20)),
                ('cohort_schema', models.PositiveIntegerField()),
                ('cohort_hash', models.CharField(max_length=64)),
                ('preview_generated_at', models.DateTimeField()),
                ('freshness_seconds', models.PositiveIntegerField()),
                ('target_group_ids_snapshot', models.JSONField(default=list)),
                ('wave_plan', models.JSONField(default=list)),
                ('total_candidates', models.PositiveIntegerField()),
                ('eligible_count', models.PositiveIntegerField()),
                ('excluded_count', models.PositiveIntegerField()),
                ('concurrency_limit', models.PositiveIntegerField(default=1)),
                ('minimum_observation_seconds', models.PositiveIntegerField(default=0)),
                ('administrative_reason', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('paused_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('aborted_at', models.DateTimeField(null=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rollout_campaigns_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rollout_campaigns_created', to=settings.AUTH_USER_MODEL)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agents.agentrelease')),
            ],
        ),
        migrations.CreateModel(
            name='AgentRolloutWave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('pending', 'pending'), ('ready', 'ready'), ('running', 'running'), ('observing', 'observing'), ('completed', 'completed'), ('paused', 'paused'), ('cancelled', 'cancelled')], default='pending', max_length=20)),
                ('resume_state', models.CharField(blank=True, max_length=20)),
                ('target_count', models.PositiveIntegerField()),
                ('minimum_observation_seconds', models.PositiveIntegerField(default=0)),
                ('eligible_target_count', models.PositiveIntegerField()),
                ('excluded_target_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(null=True)),
                ('observation_started_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waves', to='agents.agentrolloutcampaign')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='AgentRolloutTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint_machine_id_snapshot', models.CharField(blank=True, max_length=255)),
                ('endpoint_hostname_snapshot', models.CharField(blank=True, max_length=255)),
                ('current_version_snapshot', models.CharField(blank=True, max_length=100)),
                ('updater_version_snapshot', models.CharField(blank=True, max_length=100)),
                ('update_channel_snapshot', models.CharField(max_length=20)),
                ('update_policy_snapshot', models.CharField(max_length=30)),
                ('group_ids_snapshot', models.JSONField(default=list)),
                ('rollout_bucket', models.PositiveIntegerField()),
                ('eligibility_at_selection', models.BooleanField()),
                ('reason_code', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(choices=[('excluded', 'excluded'), ('eligible', 'eligible')], max_length=20)),
                ('selected_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('exclusion_metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='agents.agentjob')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='targets', to='agents.agentrolloutcampaign')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agents.agentmachine')),
                ('wave', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='targets', to='agents.agentrolloutwave')),
            ],
        ),
        migrations.AddField(
            model_name='agentrolloutcampaign',
            name='current_wave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='agents.agentrolloutwave'),
        ),
        migrations.AddConstraint(
            model_name='agentrolloutwave',
            constraint=models.UniqueConstraint(fields=('campaign', 'sequence'), name='rollout_wave_sequence'),
        ),
        migrations.AddConstraint(
            model_name='agentrolloutwave',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ['running', 'observing', 'paused'])), fields=('campaign',), name='rollout_one_active_wave'),
        ),
        migrations.AddConstraint(
            model_name='agentrolloutwave',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['pending', 'ready', 'running', 'observing', 'completed', 'paused', 'cancelled'])), name='rollout_wave_state'),
        ),
        migrations.AddConstraint(
            model_name='agentrolloutwave',
            constraint=models.CheckConstraint(condition=models.Q(('eligible_target_count', models.F('target_count')), ('excluded_target_count', 0), ('sequence__gte', 1), ('target_count__gte', 1)), name='rollout_wave_counts'),
        ),
        migrations.AddConstraint(
            model_name='agentrollouttarget',
            constraint=models.UniqueConstraint(fields=('campaign', 'endpoint'), name='rollout_target_endpoint'),
        ),
        migrations.AddConstraint(
            model_name='agentrollouttarget',
            constraint=models.CheckConstraint(condition=models.Q(('rollout_bucket__lte', 99)), name='rollout_target_bucket'),
        ),
        migrations.AddConstraint(
            model_name='agentrollouttarget',
            constraint=models.CheckConstraint(condition=models.Q(('agent_job__isnull', True), ('completed_at__isnull', True), ('started_at__isnull', True), models.Q(models.Q(('eligibility_at_selection', True), ('state', 'eligible')), models.Q(('eligibility_at_selection', False), ('state', 'excluded'), ('wave__isnull', True)), _connector='OR')), name='rollout_target_snapshot_only'),
        ),
        migrations.AddConstraint(
            model_name='agentrolloutcampaign',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ['completed', 'aborted']), _negated=True), fields=('release',), name='rollout_one_live_campaign'),
        ),
        migrations.AddConstraint(
            model_name='agentrolloutcampaign',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['draft', 'ready', 'running', 'paused', 'completed', 'aborted'])), name='rollout_campaign_state'),
        ),
        migrations.AddConstraint(
            model_name='agentrolloutcampaign',
            constraint=models.CheckConstraint(condition=models.Q(('concurrency_limit__gte', 1)), name='rollout_concurrency_positive'),
        ),
        migrations.AddConstraint(
            model_name='agentrolloutcampaign',
            constraint=models.CheckConstraint(condition=models.Q(('total_candidates', django.db.models.expressions.CombinedExpression(models.F('eligible_count'), '+', models.F('excluded_count')))), name='rollout_candidate_counts'),
        ),
        migrations.RunPython(install_guards, remove_guards),
    ]
