# Generated by Django 6.0.5 on 2026-09-17 19:00

import importlib
from django.db import migrations, models

legacy = importlib.import_module('agents.migrations.0031_agentrolloutcampaign_agentrolloutwave_and_more')


def check_forward(apps, schema_editor):
    target = apps.get_model('agents', 'AgentRolloutTarget')
    if target.objects.using(schema_editor.connection.alias).filter(state='eligible', wave__isnull=True).exists():
        raise RuntimeError('ROLLOUT_WAVE_ASSIGNMENT_REQUIRED: complete draft wave assignments before migration 0032')


def check_reverse(apps, schema_editor):
    target = apps.get_model('agents', 'AgentRolloutTarget')
    if target.objects.using(schema_editor.connection.alias).exclude(state__in=['eligible', 'excluded']).exists() or target.objects.using(schema_editor.connection.alias).filter(agent_job__isnull=False).exists():
        raise RuntimeError('ROLLBACK_UNSAFE: runtime rollout targets cannot be represented by migration 0031')


def remove_runtime_guards(apps, schema_editor):
    legacy.remove_guards(apps, schema_editor)
    table = apps.get_model('agents', 'AgentRolloutTarget')._meta.db_table
    for name in ('target_transition', 'target_binding'):
        name = 'rollout_guard_' + name
        if schema_editor.connection.vendor == 'sqlite':
            schema_editor.execute(f'DROP TRIGGER IF EXISTS {name}')
        else:
            schema_editor.execute(f'DROP TRIGGER IF EXISTS {name} ON {table}')
            schema_editor.execute(f'DROP FUNCTION IF EXISTS {name}()')


def install_runtime_guards(apps, schema_editor):
    legacy.install_guards(apps, schema_editor)
    target = apps.get_model('agents', 'AgentRolloutTarget')
    table = target._meta.db_table
    campaign = apps.get_model('agents', 'AgentRolloutCampaign')._meta.db_table
    pg = schema_editor.connection.vendor == 'postgresql'
    name = 'rollout_guard_target_freeze'
    if pg:
        schema_editor.execute(f'DROP TRIGGER {name} ON {table}')
        schema_editor.execute(f'DROP FUNCTION {name}()')
    else:
        schema_editor.execute(f'DROP TRIGGER {name}')
    mutable = {'state', 'agent_job', 'started_at', 'completed_at', 'updated_at'}
    columns = [f.column for f in target._meta.fields if f.name not in mutable]
    differs = ' OR '.join(f'OLD."{col}" IS DISTINCT FROM NEW."{col}"' if pg else f'OLD."{col}" IS NOT NEW."{col}"' for col in columns)
    rules = {
        'target_freeze': f"(EXISTS (SELECT 1 FROM {campaign} WHERE id=OLD.campaign_id AND state<>'draft') OR EXISTS (SELECT 1 FROM {campaign} WHERE id=NEW.campaign_id AND state<>'draft')) AND ({differs})",
        'target_transition': "OLD.state<>NEW.state AND NOT ((OLD.state='eligible' AND NEW.state='queued') OR (OLD.state='queued' AND NEW.state IN ('running','succeeded','failed','rolled_back','cancelled')) OR (OLD.state='running' AND NEW.state IN ('succeeded','failed','rolled_back','cancelled')))",
        'target_binding': "(OLD.agent_job_id IS NOT NULL AND (OLD.agent_job_id IS DISTINCT FROM NEW.agent_job_id OR OLD.started_at IS DISTINCT FROM NEW.started_at)) OR (OLD.completed_at IS NOT NULL AND OLD.completed_at IS DISTINCT FROM NEW.completed_at)",
    }
    for suffix, condition in rules.items():
        name = 'rollout_guard_' + suffix
        if pg:
            lock = f'PERFORM 1 FROM {campaign} WHERE id IN (OLD.campaign_id,NEW.campaign_id) ORDER BY id FOR UPDATE;'
            schema_editor.execute(f"CREATE FUNCTION {name}() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN {lock} IF {condition} THEN RAISE EXCEPTION '{name}' USING ERRCODE='23514'; END IF; RETURN NEW; END $$")
            schema_editor.execute(f'CREATE TRIGGER {name} BEFORE UPDATE ON {table} FOR EACH ROW EXECUTE FUNCTION {name}()')
        else:
            condition = condition.replace(' IS DISTINCT FROM ', ' IS NOT ')
            schema_editor.execute(f"CREATE TRIGGER {name} BEFORE UPDATE ON {table} WHEN {condition} BEGIN SELECT RAISE(ABORT,'{name}'); END")


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0031_agentrolloutcampaign_agentrolloutwave_and_more'),
    ]

    operations = [
        migrations.RunPython(check_forward, migrations.RunPython.noop),
        migrations.RunPython(legacy.remove_guards, legacy.install_guards),
        migrations.RemoveConstraint(
            model_name='agentrollouttarget',
            name='rollout_target_snapshot_only',
        ),
        migrations.AlterField(
            model_name='agentrollouttarget',
            name='state',
            field=models.CharField(choices=[('excluded', 'excluded'), ('eligible', 'eligible'), ('queued', 'queued'), ('running', 'running'), ('succeeded', 'succeeded'), ('failed', 'failed'), ('rolled_back', 'rolled_back'), ('cancelled', 'cancelled')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='agentrollouttarget',
            constraint=models.UniqueConstraint(condition=models.Q(('agent_job__isnull', False)), fields=('agent_job',), name='rollout_target_unique_job'),
        ),
        migrations.AddConstraint(
            model_name='agentrollouttarget',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('agent_job__isnull', True), ('completed_at__isnull', True), ('eligibility_at_selection', False), ('started_at__isnull', True), ('state', 'excluded'), ('wave__isnull', True)), models.Q(('agent_job__isnull', True), ('completed_at__isnull', True), ('eligibility_at_selection', True), ('started_at__isnull', True), ('state', 'eligible'), ('wave__isnull', False)), models.Q(('agent_job__isnull', False), ('eligibility_at_selection', True), ('started_at__isnull', False), ('wave__isnull', False), models.Q(models.Q(('completed_at__isnull', True), ('state__in', ['queued', 'running'])), models.Q(('completed_at__isnull', False), ('state__in', ['succeeded', 'failed', 'rolled_back', 'cancelled'])), _connector='OR')), _connector='OR'), name='rollout_target_runtime'),
        ),
        migrations.RunPython(install_runtime_guards, remove_runtime_guards),
        migrations.RunPython(migrations.RunPython.noop, check_reverse),
    ]
