# Generated by Django 6.0.5 on 2026-09-21 16:16

import importlib

from django.db import migrations, models

from agents.rollout_models import default_auto_pause_policy


runtime = importlib.import_module('agents.migrations.0032_rollout_target_execution')


def install_governance_guards(apps, schema_editor):
    runtime.install_runtime_guards(apps, schema_editor)

    campaign = apps.get_model('agents', 'AgentRolloutCampaign')
    wave = apps.get_model('agents', 'AgentRolloutWave')
    campaign_table = campaign._meta.db_table
    wave_table = wave._meta.db_table
    vendor = schema_editor.connection.vendor
    name = 'rollout_guard_wave_freeze'

    if vendor == 'postgresql':
        schema_editor.execute(f'DROP TRIGGER IF EXISTS {name} ON {wave_table}')
        schema_editor.execute(f'DROP FUNCTION IF EXISTS {name}()')
    elif vendor == 'sqlite':
        schema_editor.execute(f'DROP TRIGGER IF EXISTS {name}')
    else:
        raise RuntimeError('Rollout governance guards require SQLite or PostgreSQL')

    mutable = {
        'state',
        'resume_state',
        'updated_at',
        'started_at',
        'observation_started_at',
        'observation_accumulated_seconds',
        'observation_resumed_at',
        'completed_at',
    }
    columns = [field.column for field in wave._meta.fields if field.name not in mutable]
    operator = ' IS DISTINCT FROM ' if vendor == 'postgresql' else ' IS NOT '
    differs = ' OR '.join(f'OLD."{column}"{operator}NEW."{column}"' for column in columns)
    frozen = (
        f"EXISTS (SELECT 1 FROM {campaign_table} WHERE id=OLD.campaign_id AND state <> 'draft') "
        f"OR EXISTS (SELECT 1 FROM {campaign_table} WHERE id=NEW.campaign_id AND state <> 'draft')"
    )
    condition = f'({frozen}) AND ({differs})'

    if vendor == 'postgresql':
        lock = (
            f'PERFORM 1 FROM {campaign_table} '
            'WHERE id IN (OLD.campaign_id,NEW.campaign_id) ORDER BY id FOR UPDATE;'
        )
        schema_editor.execute(
            f"CREATE FUNCTION {name}() RETURNS trigger LANGUAGE plpgsql AS $$ "
            f"BEGIN {lock} IF {condition} THEN RAISE EXCEPTION '{name}' USING ERRCODE='23514'; "
            'END IF; RETURN NEW; END $$'
        )
        schema_editor.execute(
            f'CREATE TRIGGER {name} BEFORE UPDATE ON {wave_table} '
            f'FOR EACH ROW EXECUTE FUNCTION {name}()'
        )
    else:
        schema_editor.execute(
            f"CREATE TRIGGER {name} BEFORE UPDATE ON {wave_table} WHEN {condition} "
            f"BEGIN SELECT RAISE(ABORT, '{name}'); END"
        )


def remove_governance_guards(apps, schema_editor):
    runtime.remove_runtime_guards(apps, schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0032_rollout_target_execution'),
    ]

    operations = [
        migrations.RunPython(runtime.remove_runtime_guards, runtime.install_runtime_guards),
        migrations.AddField(
            model_name='agentrolloutcampaign',
            name='auto_pause_policy',
            field=models.JSONField(default=default_auto_pause_policy),
        ),
        migrations.AddField(
            model_name='agentrolloutwave',
            name='observation_accumulated_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agentrolloutwave',
            name='observation_resumed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(install_governance_guards, remove_governance_guards),
    ]
