# Generated by Django 6.0.5 on 2026-09-28 15:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0033_agentrolloutcampaign_auto_pause_policy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndpointPerformanceSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sample_id', models.UUIDField()),
                ('collected_at', models.DateTimeField()),
                ('cpu_percent', models.FloatField(null=True)),
                ('memory_total_bytes', models.BigIntegerField(null=True)),
                ('memory_available_bytes', models.BigIntegerField(null=True)),
                ('memory_used_percent', models.FloatField(null=True)),
                ('memory_committed_bytes', models.BigIntegerField(null=True)),
                ('memory_commit_limit_bytes', models.BigIntegerField(null=True)),
                ('memory_committed_percent', models.FloatField(null=True)),
                ('disk_active_percent', models.FloatField(null=True)),
                ('disk_queue_length', models.FloatField(null=True)),
                ('disk_read_bytes_per_sec', models.FloatField(null=True)),
                ('disk_write_bytes_per_sec', models.FloatField(null=True)),
                ('disk_read_latency_ms', models.FloatField(null=True)),
                ('disk_write_latency_ms', models.FloatField(null=True)),
                ('network_received_bytes', models.BigIntegerField(null=True)),
                ('network_sent_bytes', models.BigIntegerField(null=True)),
                ('uptime_seconds', models.BigIntegerField()),
                ('process_consumers', models.JSONField(default=dict)),
                ('collection_duration_ms', models.BigIntegerField()),
                ('agent_working_set_bytes', models.BigIntegerField(null=True)),
                ('telemetry_errors_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_samples', to='agents.agentmachine')),
            ],
            options={
                'indexes': [models.Index(fields=['endpoint', '-collected_at'], name='endpoint_perf_time_idx')],
                'constraints': [models.UniqueConstraint(fields=('endpoint', 'sample_id'), name='uniq_endpoint_telemetry_sample')],
            },
        ),
    ]
