# Generated by Django 6.0.5 on 2026-09-29 17:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0034_endpointperformancesample'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentJobResultReceiptProgression',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payload_sha256', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('job_status', models.CharField(max_length=32)),
                ('update_id', models.CharField(blank=True, max_length=80)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='agents.agentjobresultreceipt')),
            ],
            options={
                'ordering': ['received_at'],
                'constraints': [models.UniqueConstraint(fields=('receipt', 'payload_sha256'), name='uniq_job_receipt_progression_hash')],
            },
        ),
    ]
