<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NightOwl.Agent.Shared\NightOwl.Agent.Shared.csproj" />
    <ProjectReference Include="..\NightOwl.Agent.Windows\NightOwl.Agent.Windows.csproj" />
    <ProjectReference Include="..\NightOwl.Agent.Uninstaller\NightOwl.Agent.Uninstaller.csproj" />
  </ItemGroup>
</Project>
