# Generated by Django 6.0.5 on 2026-07-08 19:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0015_maintenancerun_maintenancetaskresult'),
        ('tickets', '0010_inboundemailmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planejada'), ('open', 'Aberta'), ('scheduled', 'Agendada'), ('in_progress', 'Em andamento'), ('waiting', 'Aguardando'), ('completed', 'Concluida'), ('done', 'Concluida'), ('cancelled', 'Cancelada'), ('resolved', 'Resolvida')], default='open', max_length=32)),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('normal', 'Normal'), ('high', 'Alta'), ('critical', 'Critica')], default='normal', max_length=20)),
                ('category', models.CharField(choices=[('support', 'Suporte'), ('maintenance', 'Manutencao'), ('security', 'Seguranca'), ('inventory', 'Inventario'), ('onboarding', 'Onboarding'), ('offboarding', 'Offboarding'), ('change', 'Mudanca')], default='support', max_length=40)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('responsible', models.CharField(blank=True, max_length=160)),
                ('linked_ticket_ref', models.CharField(blank=True, max_length=80)),
                ('linked_endpoint_name', models.CharField(blank=True, max_length=180)),
                ('linked_user', models.CharField(blank=True, max_length=180)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('checklist', models.JSONField(blank=True, default=list)),
                ('job_ids', models.JSONField(blank=True, default=list)),
                ('timeline', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_tasks', to='agents.agentmachine')),
                ('linked_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_tasks', to='tickets.ticket')),
            ],
            options={
                'ordering': ['due_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskReminderLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reminder_type', models.CharField(choices=[('7d', '7 dias'), ('3d', '3 dias'), ('8h', '8 horas')], max_length=8)),
                ('sent_to', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('sent', 'Enviado'), ('failed', 'Falhou')], max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='dashboard.operationaltask')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='operationaltask',
            index=models.Index(fields=['status', 'due_at'], name='dashboard_o_status_7d1224_idx'),
        ),
        migrations.AddIndex(
            model_name='operationaltask',
            index=models.Index(fields=['due_at'], name='dashboard_o_due_at_fe7abf_idx'),
        ),
        migrations.AddIndex(
            model_name='operationaltask',
            index=models.Index(fields=['responsible'], name='dashboard_o_respons_eea972_idx'),
        ),
        migrations.AddIndex(
            model_name='taskreminderlog',
            index=models.Index(fields=['reminder_type', 'status'], name='dashboard_t_reminde_acb880_idx'),
        ),
        migrations.AddIndex(
            model_name='taskreminderlog',
            index=models.Index(fields=['sent_to'], name='dashboard_t_sent_to_07763f_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskreminderlog',
            constraint=models.UniqueConstraint(fields=('task', 'reminder_type', 'sent_to'), name='unique_task_reminder_recipient'),
        ),
    ]
