# Generated by Django 6.0.5 on 2026-10-03 18:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0035_agentjobresultreceiptprogression'),
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteInstallJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_hostname', models.CharField(max_length=255)),
                ('target_fqdn', models.CharField(max_length=512)),
                ('target_ad_dn', models.CharField(max_length=1024)),
                ('status', models.CharField(default='QUEUED', max_length=32)),
                ('stage', models.CharField(default='QUEUED', max_length=32)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('active_slot', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('runner_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agentmachine')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_fqdn', '-created_at'], name='dashboard_r_target__93fbe2_idx')],
            },
        ),
    ]
