# Generated by Django 6.0.8 on 2026-10-06 02:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remoteinstalljob_diagnostics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteInstallBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='QUEUED', max_length=32)),
                ('active_slot', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('waiting_count', models.PositiveIntegerField(default=0)),
                ('current_index', models.PositiveIntegerField(default=0)),
                ('runner_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnostics', models.JSONField(blank=True, default=dict)),
                ('parent_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.remoteinstallbatch')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RemoteInstallBatchItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_hostname', models.CharField(max_length=255)),
                ('target_fqdn', models.CharField(max_length=512)),
                ('target_ad_dn', models.CharField(max_length=1024)),
                ('position', models.PositiveIntegerField()),
                ('status', models.CharField(default='WAITING', max_length=32)),
                ('stage', models.CharField(default='WAITING', max_length=32)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('progress_percentage', models.PositiveSmallIntegerField(default=0)),
                ('progress_message', models.CharField(blank=True, max_length=160)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.remoteinstallbatch')),
                ('remote_install_job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.remoteinstalljob')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('batch', 'target_fqdn'), name='remote_batch_target_unique'), models.UniqueConstraint(fields=('batch', 'position'), name='remote_batch_position_unique')],
            },
        ),
    ]
