"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import environ

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DJANGO_DEBUG=(bool, True),
    DJANGO_ALLOWED_HOSTS=(list, ['*']),
    DJANGO_CSRF_TRUSTED_ORIGINS=(list, []),
)

env_file = BASE_DIR / '.env'
if env_file.exists():
    environ.Env.read_env(env_file)


PUBLIC_NIGHTOWL_URL = 'https://nightowl.controlsul.com.br'
PUBLIC_NIGHTOWL_HOST = 'nightowl.controlsul.com.br'


def clean_env_list(name, default=None):
    values = env.list(name, default=default or [])
    cleaned = []
    for value in values:
        item = str(value or '').strip()
        if item and item not in cleaned:
            cleaned.append(item)
    return cleaned


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env(
    'DJANGO_SECRET_KEY',
    default='django-insecure-rf)kc(p+3jf71*prhdcwpa7u&xdbzy%f%zaz8g=xr5e(i_-tmz',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DJANGO_DEBUG')

ALLOWED_HOSTS = clean_env_list('DJANGO_ALLOWED_HOSTS', default=['*'] if DEBUG else [PUBLIC_NIGHTOWL_HOST])
if '*' not in ALLOWED_HOSTS and PUBLIC_NIGHTOWL_HOST not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(PUBLIC_NIGHTOWL_HOST)

CSRF_TRUSTED_ORIGINS = clean_env_list('DJANGO_CSRF_TRUSTED_ORIGINS', default=[])
if PUBLIC_NIGHTOWL_URL not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS.append(PUBLIC_NIGHTOWL_URL)

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'agents',
    'dashboard',
    'tickets',
    'access_inventory',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'config.middleware.LoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = env('DATABASE_URL', default='')

if DATABASE_URL:
    DATABASES = {
        'default': env.db('DATABASE_URL'),
    }
elif env('POSTGRES_DB', default=''):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': env('POSTGRES_DB'),
            'USER': env('POSTGRES_USER', default='nightowl'),
            'PASSWORD': env('POSTGRES_PASSWORD', default=''),
            'HOST': env('POSTGRES_HOST', default='localhost'),
            'PORT': env('POSTGRES_PORT', default='5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = env('DJANGO_TIME_ZONE', default='America/Sao_Paulo')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': env(
            'DJANGO_STATICFILES_STORAGE',
            default='whitenoise.storage.CompressedStaticFilesStorage',
        ),
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOG_DIR = BASE_DIR / 'logs'
LOG_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} {module}:{lineno} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'django_errors_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'django-errors.log',
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'verbose',
            'level': 'ERROR',
        },
    },
    'loggers': {
        'django.request': {
            'handlers': ['console', 'django_errors_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console', 'django_errors_file'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

AUTHENTICATION_BACKENDS = [
    'config.auth_backends.ActiveDirectoryBackend',
    'django.contrib.auth.backends.ModelBackend',
]
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/tickets/'
LOGOUT_REDIRECT_URL = '/accounts/login/'
NIGHTOWL_TECHNICAL_USERNAMES = {
    item.strip().casefold()
    for item in env.list('NIGHTOWL_TECHNICAL_USERNAMES', default=['gabriel.oliveira'])
    if item.strip()
}
ACCESS_INVENTORY_ALLOWED_OUS = {
    item.strip().casefold()
    for item in env.list('ACCESS_INVENTORY_ALLOWED_OUS', default=['OU=USUARIOS', 'OU=SOCIOS'])
    if item.strip()
}

# Global e-mail outbox. Credentials are read only from the environment.
EMAIL_BACKEND = env(
    'EMAIL_BACKEND',
    default='django.core.mail.backends.smtp.EmailBackend',
)
EMAIL_HOST = env('EMAIL_HOST', default='')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
EMAIL_USE_SSL = env.bool('EMAIL_USE_SSL', default=False)
EMAIL_TIMEOUT = env.int('EMAIL_TIMEOUT', default=20)
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER)
SERVER_EMAIL = env('SERVER_EMAIL', default=DEFAULT_FROM_EMAIL)
NIGHTOWL_PUBLIC_URL = env('NIGHTOWL_PUBLIC_URL', default=PUBLIC_NIGHTOWL_URL).strip().rstrip('/')
TASK_REMINDER_RECIPIENTS = env.list(
    'TASK_REMINDER_RECIPIENTS',
    default=['gabriel.oliveira@controlsul.com.br'],
)

INBOUND_EMAIL_ENABLED = env.bool('INBOUND_EMAIL_ENABLED', default=False)
INBOUND_EMAIL_HOST = env('INBOUND_EMAIL_HOST', default='')
INBOUND_EMAIL_PORT = env.int('INBOUND_EMAIL_PORT', default=993)
INBOUND_EMAIL_USER = env('INBOUND_EMAIL_USER', default='')
INBOUND_EMAIL_PASSWORD = env('INBOUND_EMAIL_PASSWORD', default='')
INBOUND_EMAIL_USE_SSL = env.bool('INBOUND_EMAIL_USE_SSL', default=True)
INBOUND_EMAIL_FOLDER = env('INBOUND_EMAIL_FOLDER', default='INBOX')
INBOUND_EMAIL_PROCESSED_FOLDER = env('INBOUND_EMAIL_PROCESSED_FOLDER', default='NightOwl/Processed')
INBOUND_EMAIL_ERROR_FOLDER = env('INBOUND_EMAIL_ERROR_FOLDER', default='NightOwl/Error')
INBOUND_EMAIL_TIMEOUT = env.int('INBOUND_EMAIL_TIMEOUT', default=30)

NIGHTOWL_RECOMMENDED_AGENT_VERSION = env(
    'NIGHTOWL_RECOMMENDED_AGENT_VERSION',
    default='0.1.0.7',
).strip()
NIGHTOWL_AGENT_HEARTBEAT_URL = env(
    'NIGHTOWL_AGENT_HEARTBEAT_URL',
    default=f'{NIGHTOWL_PUBLIC_URL}/api/agent/heartbeat/',
)
NIGHTOWL_AGENT_PUBLIC_SERVER_URL = env(
    'NIGHTOWL_AGENT_PUBLIC_SERVER_URL',
    default=NIGHTOWL_PUBLIC_URL,
).strip().rstrip('/')
NIGHTOWL_AGENT_INSTALLER_URL = env(
    'NIGHTOWL_AGENT_INSTALLER_URL',
    default=f'{NIGHTOWL_PUBLIC_URL}/downloads/nightowl-agent/Install-NightOwlAgentDotNet.ps1',
).strip()
NIGHTOWL_AGENT_SOURCE_PATH = env(
    'NIGHTOWL_AGENT_SOURCE_PATH',
    default=r'\\192.168.104.120\controlsul\Comum\_Agents',
)

AD_AUTH_ENABLED = env.bool('AD_AUTH_ENABLED', default=False)
AD_AUTH_CONFIG = {
    'ENABLED': AD_AUTH_ENABLED,
    'SERVER_URI': env('AD_SERVER_URI', default=''),
    'DOMAIN': env('AD_DOMAIN', default=''),
    'REALM': env('AD_REALM', default=''),
    'BIND_DN': env('AD_BIND_DN', default=''),
    'BIND_PASSWORD': env('AD_BIND_PASSWORD', default=''),
    'USER_SEARCH_BASE': env('AD_USER_SEARCH_BASE', default=''),
    'GROUP_SEARCH_BASE': env('AD_GROUP_SEARCH_BASE', default=''),
    'USER_ATTR': env('AD_USER_ATTR', default='sAMAccountName'),
    'EMAIL_ATTR': env('AD_EMAIL_ATTR', default='mail'),
    'FIRST_NAME_ATTR': env('AD_FIRST_NAME_ATTR', default='givenName'),
    'LAST_NAME_ATTR': env('AD_LAST_NAME_ATTR', default='sn'),
    'REQUIRE_TLS': env.bool('AD_REQUIRE_TLS', default=False),
    'ADMIN_GROUP': env('AD_ADMIN_GROUP', default=''),
    'TECH_GROUP': env('AD_TECH_GROUP', default=''),
    'TIMEOUT': env.int('AD_TIMEOUT', default=8),
}
