# Generated by Django 6.0.5 on 2026-06-11 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0015_maintenancerun_maintenancetaskresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=2048)),
                ('parent_path', models.CharField(blank=True, max_length=2048)),
                ('inheritance_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['share__unc_path', 'path'],
            },
        ),
        migrations.CreateModel(
            name='ADOrganizationalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distinguished_name', models.CharField(max_length=1024, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('parent_distinguished_name', models.CharField(blank=True, max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['distinguished_name'],
                'indexes': [models.Index(fields=['name'], name='access_inve_name_eec8c9_idx'), models.Index(fields=['parent_distinguished_name'], name='access_inve_parent__64d427_idx')],
            },
        ),
        migrations.CreateModel(
            name='ADGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=255, unique=True)),
                ('sam_account_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('distinguished_name', models.CharField(blank=True, max_length=1024, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ou', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='access_inventory.adorganizationalunit')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ADUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=255, unique=True)),
                ('sam_account_name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('user_principal_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('distinguished_name', models.CharField(blank=True, max_length=1024, null=True, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ou', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='access_inventory.adorganizationalunit')),
            ],
            options={
                'ordering': ['sam_account_name'],
            },
        ),
        migrations.CreateModel(
            name='ADGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_memberships', to='access_inventory.adgroup')),
                ('parent_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='access_inventory.adgroup')),
                ('member_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='access_inventory.aduser')),
            ],
            options={
                'ordering': ['parent_group__name', 'member_user__sam_account_name', 'member_group__name'],
            },
        ),
        migrations.CreateModel(
            name='FileServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fqdn', models.CharField(blank=True, max_length=512)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rmm_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_inventory_file_servers', to='agents.agentmachine')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AclEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_sid', models.CharField(blank=True, max_length=255)),
                ('identity_name', models.CharField(max_length=512)),
                ('identity_type', models.CharField(choices=[('user', 'User'), ('group', 'Group'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('rights', models.TextField()),
                ('access_type', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny')], default='allow', max_length=10)),
                ('inherited', models.BooleanField(default=False)),
                ('inheritance_flags', models.CharField(blank=True, max_length=255)),
                ('propagation_flags', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ad_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acl_entries', to='access_inventory.adgroup')),
                ('ad_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acl_entries', to='access_inventory.aduser')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acl_entries', to='access_inventory.folder')),
            ],
            options={
                'ordering': ['folder__path', 'identity_name', 'access_type', 'rights'],
            },
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unc_path', models.CharField(max_length=1024, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='access_inventory.fileserver')),
            ],
            options={
                'ordering': ['file_server__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='folder',
            name='share',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='access_inventory.share'),
        ),
        migrations.AddIndex(
            model_name='adgroup',
            index=models.Index(fields=['sam_account_name'], name='access_inve_sam_acc_e298b3_idx'),
        ),
        migrations.AddIndex(
            model_name='adgroup',
            index=models.Index(fields=['name'], name='access_inve_name_a74e9c_idx'),
        ),
        migrations.AddIndex(
            model_name='aduser',
            index=models.Index(fields=['sam_account_name'], name='access_inve_sam_acc_a31e2b_idx'),
        ),
        migrations.AddIndex(
            model_name='aduser',
            index=models.Index(fields=['display_name'], name='access_inve_display_3f8f01_idx'),
        ),
        migrations.AddIndex(
            model_name='aduser',
            index=models.Index(fields=['enabled'], name='access_inve_enabled_73f88a_idx'),
        ),
        migrations.AddConstraint(
            model_name='adgroupmembership',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('member_user__isnull', False), ('member_group__isnull', True)), models.Q(('member_user__isnull', True), ('member_group__isnull', False)), _connector='OR'), name='membership_has_one_member_type'),
        ),
        migrations.AddConstraint(
            model_name='adgroupmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('member_user__isnull', False)), fields=('parent_group', 'member_user'), name='unique_parent_group_member_user'),
        ),
        migrations.AddConstraint(
            model_name='adgroupmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('member_group__isnull', False)), fields=('parent_group', 'member_group'), name='unique_parent_group_member_group'),
        ),
        migrations.AddIndex(
            model_name='fileserver',
            index=models.Index(fields=['name'], name='access_inve_name_ee743f_idx'),
        ),
        migrations.AddIndex(
            model_name='fileserver',
            index=models.Index(fields=['fqdn'], name='access_inve_fqdn_ad231d_idx'),
        ),
        migrations.AddConstraint(
            model_name='fileserver',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_file_server_name'),
        ),
        migrations.AddIndex(
            model_name='aclentry',
            index=models.Index(fields=['identity_sid'], name='access_inve_identit_6f2cfd_idx'),
        ),
        migrations.AddIndex(
            model_name='aclentry',
            index=models.Index(fields=['identity_name'], name='access_inve_identit_bb4a70_idx'),
        ),
        migrations.AddIndex(
            model_name='aclentry',
            index=models.Index(fields=['identity_type'], name='access_inve_identit_dff6ce_idx'),
        ),
        migrations.AddIndex(
            model_name='aclentry',
            index=models.Index(fields=['access_type'], name='access_inve_access__a4eb64_idx'),
        ),
        migrations.AddIndex(
            model_name='aclentry',
            index=models.Index(fields=['inherited'], name='access_inve_inherit_3d51cc_idx'),
        ),
        migrations.AddConstraint(
            model_name='aclentry',
            constraint=models.UniqueConstraint(fields=('folder', 'identity_sid', 'identity_name', 'rights', 'access_type', 'inherited', 'inheritance_flags', 'propagation_flags', 'source'), name='unique_acl_entry_per_folder_identity_rights'),
        ),
        migrations.AddIndex(
            model_name='share',
            index=models.Index(fields=['file_server', 'name'], name='access_inve_file_se_a023b1_idx'),
        ),
        migrations.AddIndex(
            model_name='share',
            index=models.Index(fields=['unc_path'], name='access_inve_unc_pat_634c30_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['share', 'path'], name='access_inve_share_i_7daac2_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['parent_path'], name='access_inve_parent__7d83fc_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['inheritance_enabled'], name='access_inve_inherit_070099_idx'),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(fields=('share', 'path'), name='unique_folder_per_share'),
        ),
    ]
