# Generated by Django 6.0.5 on 2026-06-11 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('hostname', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'hostname'],
                'indexes': [models.Index(fields=['enabled', 'hostname'], name='access_inve_enabled_2a9991_idx'), models.Index(fields=['last_seen_at'], name='access_inve_last_se_8d160d_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryAgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_type', models.CharField(choices=[('file_acl', 'File ACL'), ('ad_inventory', 'AD Inventory'), ('heartbeat', 'Heartbeat')], max_length=30)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial_success', 'Partial success'), ('failed', 'Failed')], default='running', max_length=30)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('items_created', models.PositiveIntegerField(default=0)),
                ('items_updated', models.PositiveIntegerField(default=0)),
                ('items_ignored', models.PositiveIntegerField(default=0)),
                ('errors_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='access_inventory.inventoryagent')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['agent', '-started_at'], name='access_inve_agent_i_ce753d_idx'), models.Index(fields=['run_type', 'status'], name='access_inve_run_typ_6aed75_idx'), models.Index(fields=['status', '-started_at'], name='access_inve_status_7fd62c_idx')],
            },
        ),
    ]
