# Generated by Django 6.0.5 on 2026-06-15 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_inventory', '0002_inventoryagent_inventoryagentrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='aclentry',
            name='resolved_ad_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_acl_entries', to='access_inventory.adgroup'),
        ),
        migrations.AddField(
            model_name='aclentry',
            name='resolved_ad_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_acl_entries', to='access_inventory.aduser'),
        ),
        migrations.AddField(
            model_name='aclentry',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aclentry',
            name='resolved_identity_type',
            field=models.CharField(choices=[('user', 'User'), ('group', 'Group'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddIndex(
            model_name='aclentry',
            index=models.Index(fields=['resolved_identity_type'], name='access_inve_resolve_336632_idx'),
        ),
        migrations.AddIndex(
            model_name='aclentry',
            index=models.Index(fields=['resolved_at'], name='access_inve_resolve_6559b3_idx'),
        ),
    ]
