# Generated by Django 6.0.5 on 2026-06-17 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_inventory', '0003_aclentry_resolved_ad_group_aclentry_resolved_ad_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessReviewPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('approved', 'Approved'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('current_snapshot_label', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_review_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AccessReviewFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('proposed_path', models.CharField(max_length=2048)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_folders', to='access_inventory.folder')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='access_inventory.accessreviewfolder')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='access_inventory.accessreviewplan')),
            ],
            options={
                'ordering': ['plan', 'area_name', 'sort_order', 'proposed_path'],
            },
        ),
        migrations.CreateModel(
            name='AccessReviewPrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_type', models.CharField(choices=[('user', 'User'), ('group', 'Group')], max_length=20)),
                ('display_name', models.CharField(max_length=255)),
                ('sam_account_name', models.CharField(blank=True, max_length=255)),
                ('proposed_group_name', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ad_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_principals', to='access_inventory.adgroup')),
                ('ad_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_principals', to='access_inventory.aduser')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principals', to='access_inventory.accessreviewplan')),
            ],
            options={
                'ordering': ['plan', 'principal_type', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='AccessReviewRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_level', models.CharField(choices=[('none', 'Sem acesso'), ('ro', 'Somente leitura'), ('rw', 'Leitura e escrita'), ('full', 'Controle total'), ('custom', 'Personalizada')], default='none', max_length=20)),
                ('permission_label', models.CharField(blank=True, max_length=255)),
                ('permission_explanation', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('spreadsheet', 'Spreadsheet'), ('imported', 'Imported')], default='manual', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='access_inventory.accessreviewfolder')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='access_inventory.accessreviewplan')),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='access_inventory.accessreviewprincipal')),
            ],
            options={
                'ordering': ['plan', 'folder__proposed_path', 'principal__display_name'],
            },
        ),
        migrations.AddIndex(
            model_name='accessreviewplan',
            index=models.Index(fields=['status', '-updated_at'], name='access_inve_status_1064c3_idx'),
        ),
        migrations.AddIndex(
            model_name='accessreviewplan',
            index=models.Index(fields=['name'], name='access_inve_name_db394a_idx'),
        ),
        migrations.AddIndex(
            model_name='accessreviewfolder',
            index=models.Index(fields=['plan', 'area_name'], name='access_inve_plan_id_4eea37_idx'),
        ),
        migrations.AddIndex(
            model_name='accessreviewfolder',
            index=models.Index(fields=['plan', 'sort_order'], name='access_inve_plan_id_0fb140_idx'),
        ),
        migrations.AddIndex(
            model_name='accessreviewfolder',
            index=models.Index(fields=['proposed_path'], name='access_inve_propose_1b1d3e_idx'),
        ),
        migrations.AddConstraint(
            model_name='accessreviewfolder',
            constraint=models.UniqueConstraint(fields=('plan', 'proposed_path'), name='unique_review_folder_per_plan_path'),
        ),
        migrations.AddIndex(
            model_name='accessreviewprincipal',
            index=models.Index(fields=['plan', 'principal_type'], name='access_inve_plan_id_5ceef8_idx'),
        ),
        migrations.AddIndex(
            model_name='accessreviewprincipal',
            index=models.Index(fields=['display_name'], name='access_inve_display_870422_idx'),
        ),
        migrations.AddIndex(
            model_name='accessreviewprincipal',
            index=models.Index(fields=['sam_account_name'], name='access_inve_sam_acc_c2722b_idx'),
        ),
        migrations.AddIndex(
            model_name='accessreviewprincipal',
            index=models.Index(fields=['proposed_group_name'], name='access_inve_propose_6727d1_idx'),
        ),
        migrations.AddIndex(
            model_name='accessreviewrule',
            index=models.Index(fields=['plan', 'permission_level'], name='access_inve_plan_id_4188d5_idx'),
        ),
        migrations.AddIndex(
            model_name='accessreviewrule',
            index=models.Index(fields=['source'], name='access_inve_source_223cfb_idx'),
        ),
        migrations.AddConstraint(
            model_name='accessreviewrule',
            constraint=models.UniqueConstraint(fields=('plan', 'folder', 'principal'), name='unique_review_rule_per_plan_folder_principal'),
        ),
    ]
