# Generated by Django 6.0.4 on 2026-06-10 19:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0015_maintenancerun_maintenancetaskresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ticket category',
                'verbose_name_plural': 'Ticket categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField(editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('new', 'Novo'), ('in_progress', 'Em atendimento'), ('waiting_user', 'Aguardando usuario'), ('waiting_third_party', 'Aguardando terceiro'), ('resolved', 'Resolvido'), ('closed', 'Fechado'), ('canceled', 'Cancelado')], default='new', max_length=40)),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('normal', 'Normal'), ('high', 'Alta'), ('critical', 'Critica')], default='normal', max_length=30)),
                ('requester_name', models.CharField(blank=True, max_length=150)),
                ('requester_email', models.EmailField(blank=True, max_length=254)),
                ('requester_username', models.CharField(blank=True, max_length=150)),
                ('requester_department', models.CharField(blank=True, max_length=150)),
                ('requester_role', models.CharField(blank=True, max_length=150)),
                ('requester_is_partner', models.BooleanField(default=False)),
                ('assigned_to', models.CharField(blank=True, max_length=150)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('rmm_alert', 'RMM / Alerta'), ('endpoint', 'Endpoint'), ('future_agent_popup', 'Popup futuro do agente'), ('email', 'E-mail')], default='manual', max_length=40)),
                ('related_alert_id', models.CharField(blank=True, max_length=120)),
                ('related_policy_id', models.CharField(blank=True, max_length=120)),
                ('first_response_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='agents.agentmachine')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.ticketcategory')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_name', models.CharField(blank=True, max_length=150)),
                ('body', models.TextField()),
                ('visibility', models.CharField(choices=[('internal', 'Interno'), ('public', 'Publico')], default='internal', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.ticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', '-updated_at'], name='tickets_tic_status_130c04_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['priority', '-updated_at'], name='tickets_tic_priorit_fe4c59_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assigned_to'], name='tickets_tic_assigne_10250a_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_at'], name='tickets_tic_created_5dd600_idx'),
        ),
    ]
