# Generated by Django 6.0.5 on 2026-06-30 13:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_seed_ticket_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='endpoint_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='ticket',
            name='queue',
            field=models.CharField(blank=True, default='N1 - Atendimento', max_length=150),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('rmm_alert', 'RMM / Alerta'), ('endpoint', 'Endpoint'), ('future_agent_popup', 'Popup futuro do agente'), ('email', 'E-mail'), ('portal', 'Portal'), ('phone', 'Telefone'), ('monitoring', 'Monitoramento')], default='manual', max_length=40),
        ),
        migrations.CreateModel(
            name='TicketAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor', models.CharField(blank=True, default='Sistema', max_length=150)),
                ('event_type', models.CharField(max_length=60)),
                ('action', models.CharField(max_length=200)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ticket', '-created_at'], name='tickets_tic_ticket__4a7d1f_idx'), models.Index(fields=['event_type', '-created_at'], name='tickets_tic_event_t_7198d6_idx')],
            },
        ),
    ]
