# Generated by Django 6.0.5 on 2026-06-30 18:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_endpoint_name_ticket_queue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeskQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('responsible', models.CharField(blank=True, max_length=150)),
                ('members', models.JSONField(blank=True, default=list)),
                ('business_hours', models.CharField(blank=True, default='Comercial', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('receives_tickets', models.BooleanField(default=True)),
                ('receives_rmm', models.BooleanField(default=False)),
                ('receives_gmud', models.BooleanField(default=False)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Desk queue',
                'verbose_name_plural': 'Desk queues',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketcategory',
            name='allowed_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ticketcategory',
            name='default_priority',
            field=models.CharField(blank=True, choices=[('low', 'Baixa'), ('normal', 'Normal'), ('high', 'Alta'), ('critical', 'Critica')], default='normal', max_length=30),
        ),
        migrations.AddField(
            model_name='ticketcategory',
            name='icon',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='ticketcategory',
            name='default_queue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_categories', to='tickets.deskqueue'),
        ),
        migrations.CreateModel(
            name='DeskSLA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('normal', 'Normal'), ('high', 'Alta'), ('critical', 'Critica')], default='normal', max_length=30)),
                ('first_response_minutes', models.PositiveIntegerField(default=240)),
                ('resolution_minutes', models.PositiveIntegerField(default=1440)),
                ('calendar_type', models.CharField(choices=[('business_hours', 'Horario comercial'), ('24x7', '24x7')], default='business_hours', max_length=40)),
                ('pause_on_waiting_requester', models.BooleanField(default=True)),
                ('pause_on_waiting_supplier', models.BooleanField(default=False)),
                ('pause_on_waiting_approval', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('queues', models.ManyToManyField(blank=True, related_name='slas', to='tickets.deskqueue')),
            ],
            options={
                'verbose_name': 'Desk SLA',
                'verbose_name_plural': 'Desk SLAs',
                'ordering': ['resolution_minutes'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.desksla'),
        ),
        migrations.AddField(
            model_name='ticketcategory',
            name='default_sla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_categories', to='tickets.desksla'),
        ),
        migrations.CreateModel(
            name='DeskTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('template_type', models.CharField(choices=[('opening', 'Abertura'), ('public_reply', 'Resposta publica'), ('internal_comment', 'Comentario interno'), ('automatic_reply', 'Resposta automatica'), ('resolution', 'Resolucao'), ('escalation', 'Escalacao'), ('gmud', 'GMUD'), ('checklist', 'Checklist')], default='public_reply', max_length=40)),
                ('application', models.CharField(blank=True, max_length=120)),
                ('channel', models.CharField(choices=[('internal', 'Interno'), ('public', 'Publico'), ('automatic', 'Automatico'), ('approval', 'Aprovacao')], default='public', max_length=40)),
                ('trigger', models.CharField(blank=True, max_length=120)),
                ('content', models.TextField()),
                ('variables', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='tickets.ticketcategory')),
            ],
            options={
                'verbose_name': 'Desk template',
                'verbose_name_plural': 'Desk templates',
                'ordering': ['template_type', 'name'],
            },
        ),
    ]
