# Generated by Django 6.0.5 on 2026-07-01 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_deskqueue_ticket_due_at_ticketcategory_allowed_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcategory',
            name='subcategories',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
