# Generated by Django 6.0.5 on 2026-07-01 17:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_desktemplate_subject_and_applications'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=80)),
                ('channel', models.CharField(choices=[('email', 'E-mail')], default='email', max_length=30)),
                ('recipient_name', models.CharField(blank=True, max_length=150)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(blank=True, max_length=250)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviada'), ('skipped', 'Ignorada'), ('failed', 'Falhou')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_outbox', to='tickets.desktemplate')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_outbox', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Notification outbox',
                'verbose_name_plural': 'Notification outbox',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='tickets_not_status_c864a3_idx'), models.Index(fields=['ticket', '-created_at'], name='tickets_not_ticket__53a03e_idx'), models.Index(fields=['event_type', '-created_at'], name='tickets_not_event_t_619a96_idx')],
            },
        ),
    ]
