# Generated by Django 6.0.5 on 2026-07-07 18:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_ticketattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundEmailMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('from_name', models.CharField(blank=True, max_length=180)),
                ('from_email', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('processed', 'Processado'), ('skipped', 'Ignorado'), ('failed', 'Falhou')], default='processed', max_length=30)),
                ('error', models.TextField(blank=True)),
                ('raw_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_email_messages', to='tickets.ticketcomment')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_email_messages', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Inbound e-mail message',
                'verbose_name_plural': 'Inbound e-mail messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='tickets_inb_status_c0d4eb_idx'), models.Index(fields=['ticket', '-created_at'], name='tickets_inb_ticket__82d33f_idx'), models.Index(fields=['from_email', '-created_at'], name='tickets_inb_from_em_2607b4_idx')],
            },
        ),
    ]
