# Generated by Django 6.0.5 on 2026-09-16 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_inventory', '0004_accessreviewplan_accessreviewfolder_and_more'),
        ('tickets', '0010_inboundemailmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='requester_ad_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desk_tickets', to='access_inventory.aduser'),
        ),
    ]
