# Generated by Django 6.0.5 on 2026-09-17 18:42

from django.db import migrations, models


def mark_existing_requester_links_as_legacy(apps, schema_editor):
    Ticket = apps.get_model('tickets', 'Ticket')
    Ticket.objects.filter(requester_ad_user__isnull=False).update(requester_link_origin='legacy')


def leave_provenance_on_reverse(apps, schema_editor):
    # Historical links must not be reinterpreted when this migration is reversed.
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_ticket_requester_ad_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='requester_link_origin',
            field=models.CharField(blank=True, choices=[('creation', 'Criacao do chamado'), ('backfill', 'Backfill'), ('manual', 'Manual'), ('legacy', 'Legado')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='ticket',
            name='requester_linked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(mark_existing_requester_links_as_legacy, leave_provenance_on_reverse),
    ]
